options:
  charset: utf8

Company:
  columns:
    identification: string(100)
    name: string(100)
    address: string(255)
    postalcode: string(255)
    city: string(255)
    state: string(255)
    country: string(255)
    email: string(255)
    phone: string(50)
    fax: string(50)
    url: string(255)
    logo: clob
    currency: string(10)
    currency_decimals: integer
    legal_terms: clob
    pdf_orientation: string(50)
    pdf_size: string(50)
    iban: string(50)
    entity: string(50)
    office: string(50)
    control_digit: string(50)
    account: string(50)
    mercantil_registry: string(255)
    sufix: string(255)
    fiscality:
      type: boolean
      default: false
  indexes:
    cst:
      fields: [name]
      type: unique
  relations:
    CompanyUser:
      class: sfGuardUser
      foreignAlias: Users
      refClass: CompanyUser
      local: company_id
      foreign: sf_guard_user_id

CompanyUser:
  columns:
    company_id:
      type: integer
      primary: true
    sf_guard_user_id:
      type: integer(4)
      primary: true
  relations:
    Company:
      local: company_id
      foreign:  id
      foreignAlias: CompanyUser
      onDelete: cascade
    User:
      class:  sfGuardUser
      local: sf_guard_user_id
      foreign:  id
      foreignAlias: CompanyUser
      onDelete:     cascade

Customer:
  actAs:
    Taggable:
  columns:
    company_id: integer
    name: string(100)
    name_slug: string(100)
    identification: string(50)
    email: string(100)
    contact_person: string(100)
    invoicing_address: string(255)
    invoicing_postalcode: string(255)
    invoicing_city: string(255)
    invoicing_state: string(255)
    invoicing_country: string(255)
    shipping_address: string(255)
    shipping_postalcode: string(255)
    shipping_city: string(255)
    shipping_state: string(255)
    shipping_country: string(255)
    website: string(255)
    phone: string(20)
    mobile: string(20)
    fax: string(20)
    comments: clob
    iban: string(50)
    entity: string(50)
    office: string(50)
    control_digit: string(50)
    account: string(50)
    payment_type_id: integer
  indexes:
    cstm:
      fields: [company_id,name]
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
    PaymentType:
      local: payment_type_id
      foreign: id
      foreignAlias: PaymentType
      type: one
      onDelete: SET NULL

Supplier:
  columns:
    company_id: integer
    name: string(100)
    name_slug: string(100)
    identification: string(50)
    email: string(100)
    contact_person: string(100)
    invoicing_address: string(255)
    invoicing_postalcode: string(255)
    invoicing_city: string(255)
    invoicing_state: string(255)
    invoicing_country: string(255)
    website: string(255)
    phone: string(20)
    mobile: string(20)
    fax: string(20)
    comments: clob
    login: string(50)
    password: string(50)
    expense_type_id: integer
  indexes:
    cstm:
      fields: [company_id,name]
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
    ExpenseType:
      foreignAlias: Supplier
      local: expense_type_id
      foreign: id
      type: one
      onDelete: SET NULL
Common:
  actAs:
    Timestampable:
    Taggable:
  columns:
    company_id: integer
    series_id: integer
    customer_id: integer
    customer_name: string(100)
    customer_identification: string(50)
    customer_email: string(100)
    customer_phone: string(20)
    customer_fax: string(20)
    supplier_id: integer
    supplier_name: string(100)
    supplier_identification: string(50)
    supplier_email: string(100)
    supplier_phone: string(20)
    supplier_fax: string(20)
    invoicing_address: string(255)
    invoicing_postalcode: string(255)
    invoicing_city: string(255)
    invoicing_state: string(255)
    invoicing_country: string(255)
    shipping_address: string(255)
    shipping_postalcode: string(255)
    shipping_city: string(255)
    shipping_state: string(255)
    shipping_country: string(255)
    contact_person: string(100)
    terms: clob
    notes: clob
    base_amount:     { type: decimal(53), scale: 15 }
    discount_amount: { type: decimal(53), scale: 15 }
    net_amount:      { type: decimal(53), scale: 15 }
    gross_amount:    { type: decimal(53), scale: 15 }
    paid_amount:     { type: decimal(53), scale: 15 }
    tax_amount:      { type: decimal(53), scale: 15 }
    status: integer(1)
    payment_type_id: integer
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
    Customer:
      foreignAlias: Commons
      local: customer_id
      foreign: id
      type: one
      onDelete: SET NULL
    Supplier:
      foreignAlias: Commons
      local: supplier_id
      foreign: id
      type: one
      onDelete: SET NULL
    Series:
      local: series_id
      foreign: id
      onDelete: set null
    PaymentType:
      local: payment_type_id
      foreign: id
      foreignAlias: PaymentType
      type: one
      onDelete: SET NULL
  indexes:
    compny:
      fields: [company_id]
    cstnm:
      fields: [company_id,customer_name]
    cstid:
      fields: [company_id,customer_identification]
    cstml:
      fields: [company_id,customer_email]
    cntct:
      fields: [company_id,contact_person]

Invoice:
  inheritance:
    extends: Common
    type: column_aggregation
  columns:
    draft:
      type: boolean
      default: true
    # if the user wants to force the close status
    closed:
      type: boolean
      default: false
    sent_by_email:
      type: boolean
      default: false
    remesed:
      type: boolean
      default: false
    number: integer(4)
    recurring_invoice_id: integer
    estimate_id: integer
    issue_date: date
    due_date: date
  relations:
    RecurringInvoice:
      local: recurring_invoice_id
      foreign: id
      foreignAlias: Invoices
      type: one
      onDelete: SET NULL
    Estimate:
      local: estimate_id
      foreign: id
      foreignAlias: Estimate
      type: one
      onDelete: SET NULL

Expense:
  inheritance:
    extends: Common
    type: column_aggregation
  columns:
    draft:
      type: boolean
      default: true
    number: integer(4)
    recurring_invoice_id: integer
    issue_date: date
    supplier_reference: string(50)
  relations:
    RecurringInvoice:
      local: recurring_invoice_id
      foreign: id
      foreignAlias: Invoices
      type: one
      onDelete: SET NULL

Estimate:
  inheritance:
    extends: Common
    type: column_aggregation
  columns:
    draft:
      type: boolean
      default: true
    number: integer(4)
    sent_by_email:
      type: boolean
      default: false

# DEFAULT VALUES ARE MANDATORY IN ORDER TO AVOID CALCULATION
# ERRORS IN VIEWS (ARITHMETIC WITH NULL ALWAYS RETURN NULL)
Item:
  columns:
    company_id: integer
    quantity: { type: decimal(53), scale: 15, notnull: true, default: 1 }
    discount: { type: decimal(53), scale: 2, notnull: true, default: 0 }
    common_id: integer
    product_id: integer
    expense_type_id: integer
    description: clob
    unitary_cost: { type: decimal(53), scale: 15, notnull: true, default: 0 }
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
    Common:
      local: common_id
      foreign: id
      type: one
      onDelete: CASCADE
      foreignAlias: Items
    Taxes:
      class: Tax
      local: item_id
      foreign: tax_id
      refClass: ItemTax
    Product:
      local: product_id
      foreign: id
      foreignAlias: Items
      type: one
      onDelete: SET NULL
    ExpenseType:
      local: expense_type_id
      foreign: id
      foreignAlias: Items
      type: one
      onDelete: SET NULL
  indexes:
    desc:
      fields: [company_id,description]

# DEFAULT VALUES ARE MANDATORY IN ORDER TO AVOID CALCULATION
# ERRORS IN VIEWS (ARITHMETIC WITH NULL ALWAYS RETURN NULL)
Tax:
  columns:
    company_id: integer
    name: string(50)
    value: { type: decimal(53), scale: 2 }
    active:
      type: boolean
      default: true
    is_default:
      type: boolean
      default: false
    apply_total:
      type: boolean
      default: false
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
    Items:
      class: Item
      local: tax_id
      foreign: item_id
      refClass: ItemTax

ItemTax:
  columns:
    company_id: integer
    item_id:
      type: integer
      primary: true
    tax_id:
      type: integer
      primary: true
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
    Item:
      local: item_id
      foreign: id
      onDelete: CASCADE

Payment:
  columns:
    company_id: integer
    invoice_id: integer
    date: date
    amount: { type: decimal(53), scale: 15 }
    payment_type_id: integer
    notes: clob
  relations:
    PaymentType:
      local: payment_type_id
      foreign: id
      foreignAlias: PaymentType
      type: one
      onDelete: SET NULL
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
    Common:
      local: invoice_id
      foreign: id
      type: one
      foreignAlias: Payments
      onDelete: cascade

Property:
  columns:
    company_id: integer
    keey:   # I've used keey instead key because key gives problems with the sql
      type: string(50)
      primary: true
    value: clob
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE

RecurringInvoice:
  inheritance:
    extends: Common
    type: column_aggregation
  columns:
    days_to_due: integer(3)
    enabled:
      type: boolean
      default: false
    max_occurrences: integer(4)
    must_occurrences: integer(4)
    period: integer(4)
    period_type: string(8)
    starting_date:
      type: date
      default: NULL
    finishing_date:
      type: date
      default: NULL
    last_execution_date:
      type: date
      default: NULL

Profile:
  tableName: sf_guard_user_profile
  columns:
    sf_guard_user_id:   integer(4)
    first_name:         string(50)
    last_name:          string(50)
    email:
      type:   string(100)
      unique: true
    nb_display_results: integer(2)
    language:           string(3)
    country:            string(2)
    search_filter:      string(30)
    series:             string(50)
    hash:               string(50)
  relations:
    User:
      class:  sfGuardUser
      foreignType:  one
      onDelete:     cascade

Template:
  actAs:
    Timestampable:
    Sluggable:
      unique:     false
      fields:     [name]
      canUpdate:  false
  columns:
    company_id: integer
    name:         string(255)
    template:     clob
    models:        string(200)
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE

Series:
  columns:
    company_id: integer
    name:   string(255)
    value:  string(255)
    first_number:
      type: integer(4)
      default:  1
    enabled:
      type: boolean
      default: true
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE

ProductCategory:
  columns:
    company_id: integer
    name: {type: string(100), notnull: true}
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE

Product:
  actAs:
    Timestampable:
  columns:
    company_id: integer
    reference: {type: string(100), notnull: true}
    description: clob
    price: {type: decimal(53), scale: 15, notnull: true, default: 0}
    category_id: integer
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
    ProductCategory:
      local: category_id
      foreign: id
      foreignAlias: ProductCategory
      type: one
      onDelete: SET NULL

ExpenseType:
  columns:
    company_id: integer
    name:   string(255)
    enabled:
      type: boolean
      default: true
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE

PaymentType:
  columns:
    company_id: integer
    name:   string(255)
    description:   clob
    enabled:
      type: boolean
      default: true
  relations:
    Company:
      foreignAlias: Company
      local: company_id
      foreign: id
      type: one
      onDelete: CASCADE
